name: ${project.artifactId}
main: fr.k0bus.creativemanager.CreativeManager
version: ${project.version}
api-version: 1.16
softdepend:
   - Slimefun
   - ChestShop
   - Citizens
   - ItemsAdder
commands:
   cm:
      description: Commande principale !
      usage: /cm
permissions:
   creativemanager.bypass.container:
      description: "Allow using container in Creative Mode"
      default: op
   creativemanager.bypass.ignite:
      description: "Allow ignite block in Creative Mode"
      default: op
   creativemanager.bypass.spawner:
      description: "Allow using spawn-egg and place spawner in Creative Mode"
      default: op
   creativemanager.bypass.drop:
      description: "Allow drop item in Creative Mode"
      default: op
   creativemanager.bypass.pickup:
      description: "Allow pickup item in Creative Mode"
      default: op
   creativemanager.bypass.build:
      description: "Allow build/break in Creative Mode"
      default: op
   creativemanager.bypass.entity:
      description: "Allow interact with entity in Creative Mode"
      default: op
   creativemanager.bypass.inventory:
      description: "Bypass Creative Inventory Mode"
      default: op
   creativemanager.bypass.blacklist.place:
      description: "Player bypass 'place' blacklist"
      default: op
   creativemanager.bypass.blacklist.use:
      description: "Player bypass 'use' blacklist"
      default: op
   creativemanager.bypass.blacklist.get:
      description: "Player bypass 'get' blacklist"
      default: op
   creativemanager.bypass.blacklist.break:
      description: "Player bypass 'break' blacklist"
      default: op
   creativemanager.bypass.blacklist.commands:
      description: "Player bypass 'commands' blacklist"
      default: op
   creativemanager.bypass.blacklist.useblock:
      description: "Player bypass 'useblock' blacklist"
      default: op
   creativemanager.bypass.lore:
      description: "Bypass Creative Lore"
      default: op
   creativemanager.reload:
      description: "Allow reloading CreativeManager"
      default: op
   creativemanager.admin:
      description: "Allow using some admin command"
      default: op
   creativemanager.bypass.pvp:
      description: "Allow hit player"
      default: op
   creativemanager.bypass.pve:
      description: "Allow hit monster"
      default: op
   creativemanager.bypass.loot:
      description: "Allow loot creative placed block"
      default: op
   creativemanager.bypass.spawn_build:
      description: "Allow creative player to build golem"
      default: op
   creativemanager.bypass.blockcopy:
      description: "Allow creative player to copy block with NBT"
      default: op
   creativemanager.bypass.log:
      description: "Allow survival player to loot from creative placed block"
      default: op
   creativemanager.bypass.logged:
      description: "Allow creative player to bypass block logging"
      default: op
   creativemanager.bypass.custom_nbt:
      description: "Allow creative player to bypass custom NBT protection"
      default: op
   creativemanager.bypass.enchants-and-potions:
      description: "Allow creative player to bypass enchants-and-potions protection"
      default: op